Repository gdscports/react-snake, pull requests merged in 2022-10, with the labels that each got.

#10 add roadmap & spec etc to readme
  README.md
Labels: enhancement

#12 Setup React, Vite, Typescript
  web/.gitignore
  web/index.html
  web/package-lock.json
  web/package.json
  web/public/vite.svg
  web/src/App.css
  web/src/App.tsx
  web/src/assets/react.svg
  web/src/index.css
  web/src/main.tsx
  web/src/vite-env.d.ts
  web/test/.gitkeep
  web/tsconfig.json
  web/tsconfig.node.json
  web/vite.config.ts
Labels: help wanted

#9 [CI] Added Analyse Security action to check for vulnerabilities
  .github/workflows/code-security.yml
  README.md
Labels: ci

#29 Add ESLint to Web & GitHub action
  .github/workflows/lint-web.yml
  web/.eslintrc.json
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/main.tsx
Labels: ci
